services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/ishtaya/docker_volumes/php:/var/www/html
    ports:
      - "85:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - /home/ishtaya/docker_volumes/mysql:/var/lib/mysql
      - /home/ishtaya/docker_volumes/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8085:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql:

