version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    
    volumes:
      - mysql:/var/lib/mysql
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: 123 # Use environment variable

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql:

