services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/ishtaya/docker_volumes/php:/var/www/html
    ports:
      - "85:80"
    depends_on:
      - db
    restart: always
    environment:
      - SOME_ENV_VARIABLE=some_value  # Example of environment variables for the web service

  db:
    image: mysql
    restart: always
    volumes:
      - /home/ishtaya/docker_volumes/mysql:/var/lib/mysql
      - /home/ishtaya/docker_volumes/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123

volumes:
  mysql:

