services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
       volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - "85:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dictionary
      MYSQL_ROOT_PASSWORD: 123
      

volumes:
  mysql:

