services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project_php:/var/www/html
    ports:
      - "85:80"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - daat_base:/docker-entrypoint-initdb.d 
    environment:
      MYSQL_DATABASE: dictionary
      MYSQL_ROOT_PASSWORD: "123"

volumes:
  mysql:
  daat_base:
  project_php:

